### ISSUE TITLE
NullPointerException in closeTestSession when @BeforeMethod fails

### ISSUE THREAD

**Issue by renelux** [paypal/SeLion#134]
In the latest version of SeLion there is a NullPointer exception showing up when the test session gets closed. This only occurs when the @BeforeMethod fails.

Exception:

```
07.28.2015 09:02:20.180,[11] com.paypal.selion WARNING An error occurred while processing afterInvocation: null
java.lang.NullPointerException
    at com.paypal.selion.platform.grid.AbstractTestSession.closeSession(AbstractTestSession.java:236)
    at com.paypal.selion.platform.grid.SeleniumGridListener.afterInvocation(SeleniumGridListener.java:217)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
    at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

Code to reproduce:

```
   @BeforeMethod
    public void before() {
        throw new RuntimeException();
    }

    @Test
    @WebTest
    public void test(){
       //DoNothing 
    }
```

**Comment by mach6** [comment]
Also the Configuration method is not shown as failed in the `RuntimeReporter`  

For example;

``` java

    @BeforeClass
    public void beforeClass() {
        fail("failed in beforeClass");
    }

    @BeforeGroups(groups = "any")
    public void beforeGroups() {
        fail("failed in beforeGroups");
    }

    @BeforeSuite
    public void beforeSuite() {
        fail("failed in beforeSuite");
    }

    @BeforeMethod
    public void beforeMethod() {
        fail("failed in beforeMethod");
    }

    @Test(groups = "any")
    @WebTest
    public void test() {
        Grid.open("http://www.selion.io");
        assertTrue(true);
    }
```

should render a `RuntimeReport` with the following details;

``` shell
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 3 
```

instead it renders;

``` shell
  Tests run: 1, Failures: 0, Skips: 1
  Configuration Failures: 0, Skips 0
```
