### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/grid/common/exception/GridException

### ISSUE THREAD

**Issue by leilei2015** [paypal/SeLion#137]
![image](https://cloud.githubusercontent.com/assets/13569938/8980976/25774bb8-36e7-11e5-9e09-6b83f5fadf8d.png)
How to solve this issue?

07.30.2015 18:06:47.883,[1] com.paypal.selion 信息 Runtime Report : D:\workspace\mgAutoTest\target\surefire-reports\RuntimeReporter\index.html
07.30.2015 18:06:48.065,[1] com.paypal.selion 信息 JDK Information: Java HotSpot(TM) 64-Bit Server VM from Oracle Corporation ver. 1.8.0_45
07.30.2015 18:06:48.219,[11] com.paypal.selion 严重 You are trying to run a local server but are missing Jars. Do you have SeLion-Grid and Selenium-Server in your CLASSPATH?
java.lang.NoClassDefFoundError: org/openqa/grid/common/exception/GridException
    at com.paypal.selion.platform.grid.LocalGridManager.setupToBootList(LocalGridManager.java:45)
    at com.paypal.selion.platform.grid.LocalGridManager.spawnLocalHub(LocalGridManager.java:73)
    at com.paypal.selion.platform.grid.SeleniumGridListener.beforeInvocation(SeleniumGridListener.java:115)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
    at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:603)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:670)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.openqa.grid.common.exception.GridException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more

**Comment by fakrudeen78** [comment]
could you pls add following dependency in your project pom and see if it
helps

<dependency>

```
        <groupId>com.paypal.selion</groupId>


        <artifactId>SeLion-Grid</artifactId>


        <version>1.0.0-SNAPSHOT</version>


    </dependency>


    <dependency>


        <groupId>org.seleniumhq.selenium</groupId>


        <artifactId>selenium-server</artifactId>


        <version>2.45.0</version>


    </dependency>
```

With Regards,
Fakrudeen

**Comment by mach6** [comment]
Minor correction: You will need selenium-server 2.46.0 or you will run into other issues.

**Comment by leilei2015** [comment]
Thanks , Fakrudeen . The issue has been solved.That`s great! ;  Thanks mach6!
