### ISSUE TITLE
Issue during build (with test) on Java 8

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#192]
These two test failures are happening in the `DataProviders` component when Java 8 is used to build.

``` shell
FAILED: getDataAsHashtable
java.lang.AssertionError: expected object to not be null
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.assertNotNull(Assert.java:406)
    at org.testng.Assert.assertNotNull(Assert.java:391)
    at com.paypal.selion.platform.dataprovider.XmlDataProviderTest.getDataAsHashtable(XmlDataProviderTest.java:171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
SKIPPED: testDataProviderGetDataByKeys
java.lang.RuntimeException: java.lang.IllegalArgumentException: Key not found, returned null value: k2
    at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
    at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
    at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
    at org.testng.internal.Invoker.createParameters(Invoker.java:992)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Key not found, returned null value: k2
    at com.paypal.selion.platform.dataprovider.impl.DataProviderHelper.getDataByKeys(DataProviderHelper.java:393)
    at com.paypal.selion.platform.dataprovider.impl.XmlDataProviderImpl.getDataByKeys(XmlDataProviderImpl.java:276)
    at com.paypal.selion.platform.dataprovider.XmlDataProviderTest.dataProviderGetFilteredNameValueFromXmlResource(XmlDataProviderTest.java:96)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
    at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
    ... 9 more
```

**Comment by mach6** [comment]
fixed with https://github.com/paypal/SeLion/commit/1a9bf4f6e95e5682a50f345f69c8f1920fac8673
