### ISSUE TITLE
SeLion - Getting Exception : java.lang.ClassNotFoundException: org.openqa.grid.selenium.GridLauncher$GridItemLauncher

### ISSUE THREAD

**Issue by AshwinPadmanabhan** [paypal/SeLion#390]
### SeLion Version 

In POM.XML , i am using the following versions : 
a. Selenium-server : 2.46.0
2. selenium-java : 3.141.59
3. selion version - 1.0.0 

### Steps to Reproduce
Getting the following exception while running the TESTNG xml 
stacktrace : 

08.21.2019 13:56:00.167,[12] com.paypal.selion.grid.InstallHelper INFO Verifying SeLion Grid installation...
08.21.2019 13:56:00.198,[13] com.paypal.selion.grid.AbstractBaseLauncher INFO This instance is considered a SeLion Grid Hub
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org/openqa/grid/selenium/GridLauncher$GridItemLauncher
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.paypal.selion.grid.SeLionGridLauncher.<clinit>(SeLionGridLauncher.java:65)
	at com.paypal.selion.grid.ThreadedLauncher.run(ThreadedLauncher.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.openqa.grid.selenium.GridLauncher$GridItemLauncher
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 29 more
08.21.2019 13:58:01.689,[12] com.paypal.selion SEVERE Failed to start a LocalHub
org.openqa.grid.common.exception.GridException: Failed to start a LocalHub
	at com.paypal.selion.internal.platform.grid.AbstractBaseLocalServerComponent.boot(AbstractBaseLocalServerComponent.java:75)
	at com.paypal.selion.internal.platform.grid.LocalHub.boot(LocalHub.java:64)
	at com.paypal.selion.internal.platform.grid.LocalGridManager.spawnLocalHub(LocalGridManager.java:76)
	at com.paypal.selion.internal.platform.grid.SeleniumGridListener.beforeInvocation(SeleniumGridListener.java:133)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:557)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:625)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: LocalHub can not be contacted.
	at com.paypal.selion.internal.platform.grid.AbstractBaseLocalServerComponent.waitForComponentToComeUp(AbstractBaseLocalServerComponent.java:171)
	at com.paypal.selion.internal.platform.grid.AbstractBaseLocalServerComponent.boot(AbstractBaseLocalServerComponent.java:72)
	... 14 more

**Comment by mach6** [comment]
```
a. Selenium-server : 2.46.0
2. selenium-java : 3.141.59
```

These combinations are not compatible.

In addition Selenium 3.x + is not compatible with SeLion 1.x
