### ISSUE TITLE
fault handling on the browser parameter value

### ISSUE THREAD

**Issue by yunw** [paypal/SeLion#74]
In case users didn't add asterisk in the browser parameter of the suiteXmlFile:

``` xml
  <parameter name="browser" value="chrome"/>
```

 NPE will throw without indication:

``` java
Running TestSuite
02.25.2015 23:22:03.034,[1] com.paypal.selion INFO JDK Information: Java HotSpot(TM) 64-Bit Server VM from Oracle Corporation ver. 1.7.0_40
02.25.2015 23:22:03.037,[1] com.paypal.selion INFO Runtime Report : /.../surefire-reports/RuntimeReporter/index.html
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
02.25.2015 23:22:03.811,[14] com.paypal.selion INFO Local Hub spawned
02.25.2015 23:22:03.995,[14] com.paypal.selion INFO Local node spawned
02.25.2015 23:22:04.110,[14] com.paypal.selion INFO Attached node to local hub http://localhost:4444/grid/register
02.25.2015 23:22:04.120,[14] com.paypal.selion WARNING An exception occured after the test method invocation. Gobbling it as the test case itself did not fail
java.lang.NullPointerException
    at com.paypal.selion.platform.grid.Grid.wrappedDriver(Grid.java:97)
    at com.paypal.selion.reports.runtime.WebReporter.log(WebReporter.java:63)
    at com.paypal.selion.platform.grid.WebTestSession.warnUserOfTestFailures(WebTestSession.java:437)
    at com.paypal.selion.platform.grid.WebTestSession.closeCurrentSession(WebTestSession.java:410)
    at com.paypal.selion.platform.grid.SeleniumGridListener.afterInvocation(SeleniumGridListener.java:262)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
    at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
    at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:619)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:777)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
02.25.2015 23:22:04.206,[1] com.paypal.selion INFO Local hub has been stopped
02.25.2015 23:22:04.576,[1] com.paypal.selion INFO Local node has been stopped
02.25.2015 23:22:04.618,[1] com.paypal.selion INFO generating report .../surefire-reports/html/report.html
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.045 sec <<< FAILURE!
```

We should handle the exception to indicate the user mistakes.

**Comment by mach6** [comment]
This is fixed with the latest code. Furthermore, the code is now tolerant of `BROWSER = "chrome"`. Meaning the `*` is no longer required in the config value..
